name: Build and Deploy to FTP

on:
  # Se activa cuando cambios en main
  push:
    branches: [ main ]
  
  # Se activa con webhook de Contentful
  repository_dispatch:
    types: [contentful-update]

  # Permite ejecutar manualmente
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Create .env.local
      run: |
        echo "CONTENTFUL_SPACE_ID=${{ secrets.CONTENTFUL_SPACE_ID }}" >> .env.local
        echo "CONTENTFUL_ACCESS_TOKEN=${{ secrets.CONTENTFUL_ACCESS_TOKEN }}" >> .env.local
        
    - name: Build project
      run: npm run build
      
    - name: Deploy to FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./out/
        server-dir: /public_html/
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          
    - name: Notify completion
      run: |
        echo "✅ Deploy completed successfully!"
        echo "🕐 Time: $(date)"
        echo "📦 Files uploaded to FTP server" 